/**
 * Exports the canonical content to human- and machine-readable Markdown under
 * /knowledge, with YAML frontmatter.
 *
 * GENERATED, never hand-edited. The canonical knowledge is the typed, validated
 * JSON in content/ — that is what the site renders from, what the claim gate
 * filters, and what the content pipeline retrieves. /knowledge is an export of
 * it, for three audiences: a human reading the business's own facts in one
 * place, a retrieval system that prefers documents to a crawl, and a diff that
 * shows what actually changed when content moved.
 *
 * Writing these by hand would create a second source of truth, and second
 * sources of truth drift. If a file here disagrees with a page, that is a bug
 * in this script, not a content decision.
 *
 *   npm run knowledge:sync
 */
import { mkdir, writeFile, rm } from 'node:fs/promises'
import { join } from 'node:path'
import {
  getBusiness, getServices, getProducts, getLocations, getGuides, getFaqs,
  getAuthors, getSocialProfiles,
} from '@/lib/content'
import { allClaims } from '@/lib/claims'
import { site, absoluteUrl } from '@/lib/site'

const ROOT = join(process.cwd(), 'knowledge')
const TODAY = new Date().toISOString().slice(0, 10)

/** YAML frontmatter. Values are quoted so a colon in a title cannot break it. */
function frontmatter(fields: Record<string, string | string[] | undefined>): string {
  const lines = ['---']
  for (const [key, value] of Object.entries(fields)) {
    if (value === undefined) continue
    if (Array.isArray(value)) {
      if (value.length === 0) continue
      lines.push(`${key}:`)
      for (const item of value) lines.push(`  - ${JSON.stringify(item)}`)
    } else {
      lines.push(`${key}: ${JSON.stringify(value)}`)
    }
  }
  lines.push('---', '')
  return lines.join('\n')
}

const bullets = (items: string[]) => items.map((item) => `- ${item}`).join('\n')
const points = (items: Array<{ title: string; body: string }>) =>
  items.map((item) => `### ${item.title}\n\n${item.body}`).join('\n\n')

async function write(relativePath: string, body: string): Promise<void> {
  const path = join(ROOT, relativePath)
  await mkdir(join(path, '..'), { recursive: true })
  await writeFile(path, body.replace(/\n{3,}/g, '\n\n').trimEnd() + '\n', 'utf8')
}

async function main(): Promise<void> {
  // Rebuilt from scratch each run, so a renamed service cannot leave an orphan
  // document behind that a retrieval system would still find.
  await rm(ROOT, { recursive: true, force: true })
  await mkdir(ROOT, { recursive: true })

  const [business, services, products, locations, guides, faqs, authors, social] =
    await Promise.all([
      getBusiness(), getServices(), getProducts(), getLocations(), getGuides(), getFaqs(),
      getAuthors(), getSocialProfiles(),
    ])

  let written = 0

  /* --- README ------------------------------------------------------------ */
  await write(
    'README.md',
    `${frontmatter({ type: 'index', generated: TODAY })}# AquaPure UAE knowledge base

**Generated by \`npm run knowledge:sync\`. Do not edit these files.**

The canonical source is the typed, validated JSON in [content/](../content/).
This directory is an export of it: same facts, in Markdown, for reading and for
retrieval. To change anything here, change the content and re-run the sync.

| Directory | Source | Contents |
| --- | --- | --- |
| \`company/\` | content/business.json | Identity, contact, hours, coverage |
| \`services/\` | content/services.json | ${services.length} services |
| \`products/\` | content/products.json | ${products.length} products |
| \`locations/\` | content/locations.json | ${locations.length} emirates |
| \`guides/\` | content/guides.json | ${guides.length} guides |
| \`faqs/\` | content/faqs.json | ${faqs.length} questions |
| \`claims/\` | content/claims.json | ${allClaims().length} claims and their status |

Every factual assertion about the business passes through the claim registry
before it is published anywhere — including here. See [claims/README.md](claims/README.md).
`,
  )
  written++

  /* --- Company ----------------------------------------------------------- */
  await write(
    'company/aquapure-uae.md',
    `${frontmatter({
      type: 'company',
      name: business.name,
      legal_name: business.legalName,
      entity_type: business.entityType,
      url: absoluteUrl('/'),
      status: 'active',
      last_verified: TODAY,
    })}# ${business.name}

${business.description}

## Identity

- **Name**: ${business.name}
- **Legal name**: ${business.legalName}
- **Type**: ${business.entityType}
- **Website**: ${absoluteUrl('/')}
- **Phone**: ${site.phone.display} (\`${site.phone.e164}\`)
- **Email**: ${site.email}
- **Based in**: ${business.address.street}, ${business.address.city}, ${business.address.countryName}
- **Languages**: ${business.languages.join(', ')}
- **Payment**: ${business.paymentAccepted.join(', ')} (${business.currenciesAccepted})
- **Profiles**: ${social.length > 0 ? social.map((entry) => entry.url).join(', ') : '_none configured — see content/business.json_'}

## Hours

${bullets(business.hours.map((hour) => `**${hour.days}**: ${hour.time}`))}

## Coverage

${bullets(locations.map((location) => `**${location.name}** — ${location.responseTime}. ${location.responseNote} Water supplied by ${location.utility}.`))}

## Services

${bullets(services.map((service) => `[${service.title}](../services/${service.slug}.md) — ${service.short}`))}
`,
  )
  written++

  /* --- Services ---------------------------------------------------------- */
  for (const service of services) {
    await write(
      `services/${service.slug}.md`,
      `${frontmatter({
        type: 'service',
        name: service.title,
        slug: service.slug,
        service_type: service.serviceType,
        status: 'active',
        area_served: 'United Arab Emirates',
        url: absoluteUrl(`/services/${service.slug}`),
        related_services: service.relatedServices,
        related_products: service.relatedProducts,
        related_guides: service.relatedGuides,
        last_verified: TODAY,
      })}# ${service.h1}

${service.directAnswer}

## Key facts

${bullets(service.keyFacts)}

## What it involves

${service.whatItIs.join('\n\n')}

## Who needs it

${points(service.whoNeedsIt)}

## How it works

${service.howItWorks.map((step) => `### ${step.step} — ${step.title}\n\n${step.body}`).join('\n\n')}

## What is included

${bullets(service.bullets)}

## Benefits

${points(service.benefits)}

## Maintenance

${points(service.maintenance)}

## Common problems

${service.commonProblems.map((problem) => `### ${problem.problem}\n\n- **Cause**: ${problem.cause}\n- **Fix**: ${problem.fix}`).join('\n\n')}

## Choosing

${points(service.choosingFactors)}

## UAE context

${service.uaeContext.join('\n\n')}

## Cost

${service.pricingNote}
`,
    )
    written++
  }

  /* --- Products ---------------------------------------------------------- */
  for (const product of products) {
    await write(
      `products/${product.slug}.md`,
      `${frontmatter({
        type: 'product',
        name: product.name,
        slug: product.slug,
        category: product.category,
        status: 'available',
        url: absoluteUrl(`/products/${product.slug}`),
        related_services: product.relatedServices,
        related_guides: product.relatedGuides,
        last_verified: TODAY,
      })}# ${product.h1}

${product.directAnswer}

## Key facts

${bullets(product.keyFacts)}

## Features

${bullets(product.features)}

## Who it suits

${points(product.whoItSuits)}

## How it is fitted

${product.howItFits.join('\n\n')}

## Maintenance

${points(product.maintenance)}

## Considerations

${points(product.considerations)}

## Specification

${product.specNote}
`,
    )
    written++
  }

  /* --- Locations --------------------------------------------------------- */
  for (const location of locations) {
    await write(
      `locations/${location.slug}.md`,
      `${frontmatter({
        type: 'location',
        name: location.name,
        slug: location.slug,
        country: 'United Arab Emirates',
        utility: location.utility,
        response_time: location.responseTime,
        status: 'served',
        url: absoluteUrl(`/locations/${location.slug}`),
        areas: location.areas,
        priority_services: location.priorityServices,
        last_verified: TODAY,
      })}# Water filtration in ${location.name}

${location.intro}

**Typical response**: ${location.responseTime}. ${location.responseNote}

**Water supplied by**: ${location.utility}

## Areas covered

${bullets(location.areas)}

## Property types

${location.propertyMix}

## Water supply

${location.supply.join('\n\n')}

## Common requests

${points(location.commonRequests)}

## Local considerations

${points(location.localConsiderations)}

## Services most requested here

${bullets(location.priorityServices.map((slug) => `[${slug}](../services/${slug}.md)`))}
`,
    )
    written++
  }

  /* --- Guides ------------------------------------------------------------ */
  for (const guide of guides) {
    const author = authors.find((candidate) => candidate.id === guide.author)
    const body = guide.sections
      .map((section) => {
        const parts = [`## ${section.heading}`]
        if (section.paragraphs) parts.push(section.paragraphs.join('\n\n'))
        if (section.list) parts.push(points(section.list))
        if (section.slot === 'comparison' && guide.comparison) {
          const { columns, rows, caption } = guide.comparison
          parts.push(
            `_${caption}_\n`,
            `| | ${columns.join(' | ')} |`,
            `| --- | ${columns.map(() => '---').join(' | ')} |`,
            ...rows.map((row) => `| **${row.label}** | ${row.values.join(' | ')} |`),
          )
        }
        return parts.join('\n\n')
      })
      .join('\n\n')

    await write(
      `guides/${guide.slug}.md`,
      `${frontmatter({
        type: 'guide',
        title: guide.title,
        slug: guide.slug,
        category: guide.category,
        search_intent: guide.searchIntent,
        primary_question: guide.primaryQuestion,
        url: absoluteUrl(`/guides/${guide.slug}`),
        author: author?.name ?? guide.author,
        published: guide.published,
        updated: guide.updated,
        last_fact_verified: guide.lastFactVerified,
        related_services: guide.relatedServices,
        related_guides: guide.relatedGuides,
      })}# ${guide.h1}

**${guide.primaryQuestion}**

${guide.directAnswer}

## Key facts

${bullets(guide.keyFacts)}

${body}

${guide.verdict ? `## The short version\n\n${guide.verdict}\n` : ''}
`,
    )
    written++
  }

  /* --- FAQs -------------------------------------------------------------- */
  const byCategory = new Map<string, typeof faqs>()
  for (const faq of faqs) {
    byCategory.set(faq.category, [...(byCategory.get(faq.category) ?? []), faq])
  }
  for (const [category, items] of byCategory) {
    await write(
      `faqs/${category}.md`,
      `${frontmatter({
        type: 'faq-collection',
        category,
        count: String(items.length),
        url: absoluteUrl('/faqs'),
        last_verified: TODAY,
      })}# FAQs — ${category.replace(/-/g, ' ')}

${items.map((faq) => `## ${faq.q}\n\n${faq.a}\n\n_id: \`${faq.id}\` · last verified ${faq.lastVerified}_`).join('\n\n')}
`,
    )
    written++
  }

  /* --- Claims ------------------------------------------------------------ */
  const grouped = new Map<string, typeof claims>()
  const claims = allClaims()
  for (const claim of claims) {
    grouped.set(claim.status, [...(grouped.get(claim.status) ?? []), claim])
  }

  await write(
    'claims/README.md',
    `${frontmatter({
      type: 'claim-registry',
      total: String(claims.length),
      publishable: String(claims.filter((claim) => claim.allowedForPublication).length),
      generated: TODAY,
    })}# Claim registry

Every checkable statement about AquaPure, and whether it may be published.

Source: [content/claims.json](../../content/claims.json). Process: [docs/CLAIMS.md](../../docs/CLAIMS.md).

${[...grouped.entries()]
  .map(([status, list]) => {
    const publishable = list[0]?.allowedForPublication
    return `## ${status} — ${list.length} claim${list.length === 1 ? '' : 's'} ${publishable ? '(published)' : '(**not** published)'}

${list
  .map(
    (claim) =>
      `### \`${claim.id}\`\n\n> ${claim.claim}\n\n- kind: ${claim.kind}${claim.value ? `\n- value: ${claim.value}` : ''}\n- source: ${claim.source || '_none on file_'}\n- last verified: ${claim.lastVerified || '_never_'}${claim.notes ? `\n- notes: ${claim.notes}` : ''}`,
  )
  .join('\n\n')}`
  })
  .join('\n\n')}
`,
  )
  written++

  console.log(`\nwrote ${written} files to knowledge/\n`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
